package com.wolaidai.statistic.model;

import java.util.Date;

public class StatisticAgentUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_agent_users.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_agent_users.agent_code
     *
     * @mbggenerated
     */
    private String agentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_agent_users.uuid
     *
     * @mbggenerated
     */
    private Long uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_agent_users.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_agent_users.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_agent_users.id
     *
     * @return the value of statistic_agent_users.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_agent_users.id
     *
     * @param id the value for statistic_agent_users.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_agent_users.agent_code
     *
     * @return the value of statistic_agent_users.agent_code
     *
     * @mbggenerated
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_agent_users.agent_code
     *
     * @param agentCode the value for statistic_agent_users.agent_code
     *
     * @mbggenerated
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_agent_users.uuid
     *
     * @return the value of statistic_agent_users.uuid
     *
     * @mbggenerated
     */
    public Long getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_agent_users.uuid
     *
     * @param uuid the value for statistic_agent_users.uuid
     *
     * @mbggenerated
     */
    public void setUuid(Long uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_agent_users.mobile
     *
     * @return the value of statistic_agent_users.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_agent_users.mobile
     *
     * @param mobile the value for statistic_agent_users.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_agent_users.create_at
     *
     * @return the value of statistic_agent_users.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_agent_users.create_at
     *
     * @param createAt the value for statistic_agent_users.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", agentCode=").append(agentCode);
        sb.append(", uuid=").append(uuid);
        sb.append(", mobile=").append(mobile);
        sb.append(", createAt=").append(createAt);
        sb.append("]");
        return sb.toString();
    }
}