package com.wolaidai.statistic.mapper;

import com.welab.mybatis.annotation.Mapper;
import com.wolaidai.statistic.model.StatisticAgentUsers;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StatisticAgentUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    int insert(StatisticAgentUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    int insertSelective(StatisticAgentUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    StatisticAgentUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatisticAgentUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatisticAgentUsers record);

    /**
     * 此方法返回满足条件的记录数;<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> statistic_agent_users
     *
     * @mbggenerated Thu Sep 08 13:45:02 CST 2016
     */
    Integer countByModelSelective(@Param("cond") StatisticAgentUsers cond, @Param("strict") boolean strict);

    /**
     * 此方法删除满足条件的记录数;<br/>
     * 此条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> statistic_agent_users
     *
     * @mbggenerated Thu Sep 08 13:45:02 CST 2016
     */
    Integer deleteByModelSelective(@Param("cond") StatisticAgentUsers cond, @Param("strict") boolean strict);

    /**
     * 此方法根据cond设置条件更新model中设置的字段值;<br/>
     * 此条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> statistic_agent_users
     *
     * @mbggenerated Thu Sep 08 13:45:02 CST 2016
     */
    Integer updateByModelSelective(@Param("cond") StatisticAgentUsers cond, @Param("strict") boolean strict, @Param("model") StatisticAgentUsers model);

    /**
     * 此方法返回满足条件的单条记录.<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * 注意：java的Date不能完成匹配Oracle Date类型，即insert date into table 然后使用同一值date select是取不到对应记录的.<br/>
     * 
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table statistic_agent_users
     *
     * @mbggenerated Thu Sep 08 13:45:02 CST 2016
     */
    StatisticAgentUsers selectByModelSelective(@Param("cond") StatisticAgentUsers cond, @Param("strict") boolean strict);
}